[package]
name = "display-driver-spi"
version = "0.1.0"
edition = "2021"
description = "SPI bus implementation"
license = "Apache-2.0"

[dependencies]
display-driver = { path = "../../display-driver" }
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
